server:
  port: 9111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.12.238.52:3306/student_course_choosing?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 129496
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: 1.12.238.52
    port: 6379
    password: 129496
    database: 0
    jedis:
      pool: #链接池设置
        max-idle: 8
        min-idle: 0
        max-active: 8
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    
