---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ken-Chy.
--- DateTime: 2023/2/26 20:42
---

--- 比较线程标识与锁中的标识是否一致
if(redis.call('get', KEYS[1]) == ARGS[1]) then
    --- 释放锁
    return redis.call('del', KEYS[1])
end
return 0
